### ISSUE TITLE
Validating against enum

### ISSUE THREAD

**Issue by peterkronenberg** [Ge0rg3/flask-parameter-validation#44]
Is there a way to validate an argument to ensure that it has only a list of specific values?

For example

```
func(
          suit = Json(hearts | clubs | spades | diamonds)
):
```

Or maybe validate against an existing Python enum

**Comment by smt5541** [comment]
Currently, the best way to do this is the `func` parameter passed to the decorator, but I can see type hints being used for ensuring a value is in the enum to make that smoother.

**Comment by peterkronenberg** [comment]
Where are the type hints documented?  I don't recall seeing anything about arguments to the decorator

**Comment by smt5541** [comment]
Sorry, I misspoke - there are parameters that can be passed to the decorator to customize error handling. I meant to say the `func` parameter of `Parameter`'s subclasses.

Currently in the midst of fleshing out and updating documentation on [my fork](https://github.com/smt5541/flask-parameter-validation/blob/dev/smt5541/openapi/README.md) (alongside #42 ), so that may help as well.

**Comment by peterkronenberg** [comment]
Ah, I see.  An example of usage would be great.  I'll keep on eye on the docs.  Looks good so far.
